/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contoh1;

/**
 *
 * @author Laurent Glorian - 2019130004
 */
public class FrmContoh1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmContoh1
     */
    public FrmContoh1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbJumlah = new javax.swing.JLabel();
        jLbHarga = new javax.swing.JLabel();
        jBtnHit = new javax.swing.JButton();
        jTxtJumlah = new javax.swing.JTextField();
        jTxtHarga = new javax.swing.JTextField();
        jBtnHapus = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jLbBayar = new javax.swing.JLabel();
        jTxtBayar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbJumlah.setText("Jumlah");
        getContentPane().add(jLbJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 14, -1, -1));

        jLbHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbHarga.setText("Harga");
        getContentPane().add(jLbHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 55, -1, -1));

        jBtnHit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnHit.setText("Hitung");
        jBtnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 98, 60));

        jTxtJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTxtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 11, 166, -1));

        jTxtHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 52, 166, -1));

        jBtnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnHapus.setText("Hapus");
        jBtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 134, 98, 60));

        jBtnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 134, 98, 60));

        jLbBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbBayar.setText("Bayar");
        getContentPane().add(jLbBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 96, -1, -1));

        jTxtBayar.setEditable(false);
        jTxtBayar.setBackground(new java.awt.Color(255, 255, 153));
        jTxtBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTxtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 93, 166, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contoh1/balance-spendings-budget-money-save-money-icon-270546.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHitActionPerformed
        int jumlah = Integer.parseInt(jTxtJumlah.getText());
        int harga = Integer.parseInt(jTxtHarga.getText());
        int bayar = jumlah*harga;
        jTxtBayar.setText(String.valueOf(bayar));
    }//GEN-LAST:event_jBtnHitActionPerformed

    private void jBtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHapusActionPerformed
        jTxtJumlah.setText("");
        jTxtHarga.setText("");
        jTxtBayar.setText("");
        jTxtJumlah.grabFocus();
    }//GEN-LAST:event_jBtnHapusActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContoh1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnHapus;
    private javax.swing.JButton jBtnHit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbBayar;
    private javax.swing.JLabel jLbHarga;
    private javax.swing.JLabel jLbJumlah;
    private javax.swing.JTextField jTxtBayar;
    private javax.swing.JTextField jTxtHarga;
    private javax.swing.JTextField jTxtJumlah;
    // End of variables declaration//GEN-END:variables
}
